Repository jakniedojade/jakniedojade-web-gui, pull requests merged in 2024-11, with the labels that each got.

#20 Reactivity improvements in search
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
Labels: refactor

#26 Add an Azure static web app config file
  .github/workflows/azure-static-web-apps-blue-grass-0ce1a4e03.yml
  src/app/app.config.ts
  staticwebapp.config.json
Labels: bug

#28 Bug fixes
  src/app/components/map/map.component.ts
  src/app/components/search/search.component.ts
  src/app/services/line-data.service.ts
Labels: bug

#34 Fix Azure deployment action to properly remove staging environments on pull request close
  .github/workflows/azure-static-web-apps-thankful-coast-0a2e5ec03.yml
Labels: bug, enhancement

#38 Direction meanlatency settings components
  src/app/app.routes.ts
  src/app/components/direction-analysis-selection/direction-analysis-selection.component.html
  src/app/components/direction-analysis-selection/direction-analysis-selection.component.ts
  src/app/components/direction-meanlatency-route-selection/direction-meanlatency-route-selection.component.html
  src/app/components/direction-meanlatency-route-selection/direction-meanlatency-route-selection.component.scss
  src/app/components/direction-meanlatency-route-selection/direction-meanlatency-route-selection.component.spec.ts
  src/app/components/direction-meanlatency-route-selection/direction-meanlatency-route-selection.component.ts
  src/app/components/direction-meanlatency-settings/direction-meanlatency-settings.component.html
  src/app/components/direction-meanlatency-settings/direction-meanlatency-settings.component.scss
  src/app/components/direction-meanlatency-settings/direction-meanlatency-settings.component.spec.ts
  src/app/components/direction-meanlatency-settings/direction-meanlatency-settings.component.ts
  src/app/components/direction-selection/direction-selection.component.html
  src/app/components/direction-selection/direction-selection.component.ts
  src/app/components/lines-on-pole-selection/lines-on-pole-selection.component.html
  src/app/components/lines-on-pole-selection/lines-on-pole-selection.component.ts
  src/app/components/map/map.component.ts
  src/app/components/pole-analysis-selection/pole-analysis-selection.component.html
  src/app/components/pole-analysis-selection/pole-analysis-selection.component.ts
  src/app/components/results/results.component.html
  src/app/components/results/results.component.scss
  src/app/components/results/results.component.spec.ts
  src/app/components/results/results.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
  src/app/components/stop-selection/stop-selection.component.html
  src/app/components/stop-selection/stop-selection.component.scss
  src/app/components/stop-selection/stop-selection.component.spec.ts
  src/app/components/stop-selection/stop-selection.component.ts
  src/app/components/weekdays-selection/weekdays-selection.component.html
  src/app/components/weekdays-selection/weekdays-selection.component.scss
  src/app/components/weekdays-selection/weekdays-selection.component.spec.ts
  src/app/components/weekdays-selection/weekdays-selection.component.ts
  src/app/interfaces/line-data.ts
  src/app/interfaces/line-on-pole.ts
  src/app/interfaces/lines.ts
  src/app/services/line-data.service.ts
  src/app/services/lines-on-pole.service.ts
  src/app/services/lines.service.ts
  src/app/services/map.service.ts
  src/app/services/poles-on-stop.service.ts
  src/app/services/stops.service.ts
  src/assets/stop_on_request_gray.svg
  src/assets/stop_regular_gray.svg
Labels: new logic
